from typing import Any, TypeAlias

import numpy.typing as npt

ParamValue: TypeAlias = bool | int | float | str | bytes
ParamInput: TypeAlias = ParamValue | npt.NDArray[Any]

class SitosError(RuntimeError): ...
class NotFoundError(SitosError): ...
class TypeMismatchError(SitosError): ...
class TimeoutError(SitosError): ...
class DisconnectedError(SitosError): ...
class ReadOnlyError(SitosError): ...

__version__: str

def encode_value(value: ParamInput) -> bytes: ...
def decode_value(payload: bytes) -> ParamValue: ...
