from collections.abc import Iterable, Iterator, Mapping
from typing import Any, TypeAlias, overload

import numpy as np

ParamValue: TypeAlias = bool | int | float | str | bytes
ParamInput: TypeAlias = ParamValue | np.ndarray
BatchEntries: TypeAlias = Mapping[str, ParamInput] | Iterable[tuple[str, ParamInput]]

class SitosError(Exception): ...
class NotFoundError(SitosError): ...
class TypeMismatchError(SitosError): ...
class TimeoutError(SitosError): ...
class DisconnectedError(SitosError): ...
class ReadOnlyError(SitosError): ...

class ParamCache:
    def __init__(
        self,
        *,
        prefix: str = ...,
        zenoh_config_json: str | None = ...,
        query_timeout_ms: int = ...,
    ) -> None: ...
    def __enter__(self) -> ParamCache: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...
    def close(self) -> None: ...
    def attach(self, sid: str) -> None: ...
    def detach(self) -> None: ...
    def put(self, key: str, value: ParamInput) -> None: ...
    def put_batch(self, entries: BatchEntries) -> None: ...
    @overload
    def get(self, key: str, default: Any = ..., *, type: None = ...) -> ParamValue | Any: ...
    @overload
    def get(self, key: str, default: Any = ..., *, type: type[bool]) -> bool: ...
    @overload
    def get(self, key: str, default: Any = ..., *, type: type[int]) -> int: ...
    @overload
    def get(self, key: str, default: Any = ..., *, type: type[float]) -> float: ...
    @overload
    def get(self, key: str, default: Any = ..., *, type: type[str]) -> str: ...
    @overload
    def get(self, key: str, default: Any = ..., *, type: type[bytes]) -> bytes: ...
    def contains(self, key: str) -> bool: ...
    def items(self, prefix: str = ...) -> Iterator[tuple[str, ParamValue]]: ...
    def get_array(self, key: str, *, dtype: np.typing.DTypeLike) -> np.ndarray: ...
