from collections.abc import Iterable

__all__ = ["StorageEngine", "StorageReader"]

class StorageReader:
    def get(self, key: str) -> bytes | None: ...
    def list(self, prefix: str) -> Iterable[tuple[str, bytes]]: ...

class StorageEngine(StorageReader):
    def put(self, key: str, value: bytes) -> bool | None: ...
    def delete(self, key: str) -> bool | None: ...
