from collections.abc import Iterator
from typing import TypeAlias, TypeVar, overload

from ._sitos import (
    DisconnectedError as DisconnectedError,
    NotFoundError as NotFoundError,
    ParamInput as ParamInput,
    ParamValue as ParamValue,
    ReadOnlyError as ReadOnlyError,
    SitosError as SitosError,
    TimeoutError as TimeoutError,
    TypeMismatchError as TypeMismatchError,
)

_DefaultT = TypeVar("_DefaultT")

class InMemoryEngine:
    def __init__(self) -> None: ...

class SessionView:
    @overload
    def get(self, key: str, *, type: None = ...) -> ParamValue: ...
    @overload
    def get(self, key: str, *, default: _DefaultT, type: None = ...) -> ParamValue | _DefaultT: ...
    @overload
    def get(self, key: str, *, type: type[bool]) -> bool: ...
    @overload
    def get(self, key: str, *, default: _DefaultT, type: type[bool]) -> bool | _DefaultT: ...
    @overload
    def get(self, key: str, *, type: type[int]) -> int: ...
    @overload
    def get(self, key: str, *, default: _DefaultT, type: type[int]) -> int | _DefaultT: ...
    @overload
    def get(self, key: str, *, type: type[float]) -> float: ...
    @overload
    def get(self, key: str, *, default: _DefaultT, type: type[float]) -> float | _DefaultT: ...
    @overload
    def get(self, key: str, *, type: type[str]) -> str: ...
    @overload
    def get(self, key: str, *, default: _DefaultT, type: type[str]) -> str | _DefaultT: ...
    @overload
    def get(self, key: str, *, type: type[bytes]) -> bytes: ...
    @overload
    def get(self, key: str, *, default: _DefaultT, type: type[bytes]) -> bytes | _DefaultT: ...
    def contains(self, key: str) -> bool: ...
    def items(self, prefix: str = ...) -> Iterator[tuple[str, ParamValue]]: ...

class StorageNode:
    def __init__(
        self,
        engine: InMemoryEngine,
        *,
        prefix: str = ...,
        zenoh_config_json: str | None = ...,
    ) -> None: ...
    def __enter__(self) -> StorageNode: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...
    def create_session(self, sid: str) -> None: ...
    def close_session(self, sid: str) -> None: ...
    def active_sessions(self) -> list[str]: ...
    def session_view(self, sid: str) -> SessionView: ...
    def stop(self) -> None: ...
