from collections.abc import Iterable, Iterator, Mapping
from typing import TypeAlias, TypeVar, overload

from ._sitos import (
    DisconnectedError as DisconnectedError,
    NotFoundError as NotFoundError,
    ParamInput as ParamInput,
    ParamValue as ParamValue,
    ReadOnlyError as ReadOnlyError,
    SitosError as SitosError,
    TimeoutError as TimeoutError,
    TypeMismatchError as TypeMismatchError,
)

BatchEntries: TypeAlias = Mapping[str, ParamInput] | Iterable[tuple[str, ParamInput]]
_DefaultT = TypeVar("_DefaultT")

class ParamStore:
    def __init__(
        self,
        *,
        prefix: str = ...,
        zenoh_config_json: str | None = ...,
        query_timeout_ms: int = ...,
    ) -> None: ...
    def __enter__(self) -> ParamStore: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...
    def close(self) -> None: ...
    def put(self, scope: str, key: str, value: ParamInput) -> None: ...
    def put_batch(self, scope: str, entries: BatchEntries) -> None: ...
    def delete(self, scope: str, key: str) -> None: ...
    @overload
    def get(self, scope: str, key: str, *, type: None = ...) -> ParamValue: ...
    @overload
    def get(
        self, scope: str, key: str, default: _DefaultT, *, type: None = ...
    ) -> ParamValue | _DefaultT: ...
    @overload
    def get(self, scope: str, key: str, *, type: type[bool]) -> bool: ...
    @overload
    def get(
        self, scope: str, key: str, default: _DefaultT, *, type: type[bool]
    ) -> bool | _DefaultT: ...
    @overload
    def get(self, scope: str, key: str, *, type: type[int]) -> int: ...
    @overload
    def get(
        self, scope: str, key: str, default: _DefaultT, *, type: type[int]
    ) -> int | _DefaultT: ...
    @overload
    def get(self, scope: str, key: str, *, type: type[float]) -> float: ...
    @overload
    def get(
        self, scope: str, key: str, default: _DefaultT, *, type: type[float]
    ) -> float | _DefaultT: ...
    @overload
    def get(self, scope: str, key: str, *, type: type[str]) -> str: ...
    @overload
    def get(
        self, scope: str, key: str, default: _DefaultT, *, type: type[str]
    ) -> str | _DefaultT: ...
    @overload
    def get(self, scope: str, key: str, *, type: type[bytes]) -> bytes: ...
    @overload
    def get(
        self, scope: str, key: str, default: _DefaultT, *, type: type[bytes]
    ) -> bytes | _DefaultT: ...
    def contains(self, scope: str, key: str) -> bool: ...
    def list(self, scope: str, prefix: str = ...) -> Iterator[tuple[str, ParamValue]]: ...
