from typing import Literal

from ._sitos import ParamValue

__all__ = ["ParamChange", "Subscription"]

class ParamChange:
    @property
    def kind(self) -> Literal["put", "delete"]: ...
    @property
    def key(self) -> str: ...
    @property
    def value(self) -> ParamValue | None: ...
    def __init__(
        self, kind: Literal["put", "delete"], key: str, value: ParamValue | None
    ) -> None: ...

class Subscription:
    def close(self) -> None: ...
    def __enter__(self) -> Subscription: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> bool: ...
